name: reDart
description: Command-line helper program for RealmEye written in Dart.
version: 1.0.0

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  puppeteer: ^1.18.0
  ansicolor: ^1.0.2
  intl: ^0.16.1
  pedantic: ^1.9.0
